# Gradle
# Build your Java project and run tests with Gradle using a Gradle wrapper script.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: 'macOS-10.13'

steps: 
- task: CocoaPods@0
  inputs:
    forceRepoUpdate: true

- task: Xcode@5
  inputs:
    actions: 'build'
    sdk: 'iphonesimulator'
    configuration: 'Debug'
    xcWorkspacePath: 'VolleyScorer.xcworkspace'
    scheme: 'VolleyScorer'
    xcodeVersion: '10'
    args: '-derivedDataPath $(agent.buildDirectory)/build'