trigger:
  - main

pool:
  vmImage: 'macOS-latest'

  steps:
  
      - task: NodeTool@0
        inputs:
         versionSpec: "18.12.1"
        script:| 
                SIMULATOR_NAME="my-sim"
                 SIMULATOR_UDID=`xcrun simctl create "$SIMULATOR_NAME"
                 com.apple.CoreSimulator.SimDeviceType.iPhone-12 
                 com.apple.CoreSimulator.SimRuntime.iOS-14-3`
                 xcrun simctl boot $SIMULATOR_UDID
       script:|
          node -v
          java -version
          npm install -g appium@next
          appium -v
          appium driver install xcuitest
          appium plugin install --source npm appium-device-farm